

# CONFIGURACIONES DE pantalla
ANCHO, ALTO = 768, 512 # 12 tiles de ancho y 8 de alto
BLANCO = (255, 255, 255)

# FILAS Y COLUMNAS DEL NIVEL
FILAS = 8
COLUMNAS_TOTAL_NIVEL = 18
COLUMNAS = 18 * COLUMNAS_TOTAL_NIVEL

# APARTADO MUSICAL
MUSICA_MENU = "crayon_amazing_wasa_presentation1.wav"
VOLUMEN_MENU = 0.3

MUSICA_NIVEL_1 = "Cool_Cat_Highwire.mp3"
VOLUMEN_NIVEL_1 = 0.2

# TIPOS DE TILES
TILES_SOLIDOS = {10, 20, 21, 22, 23}

# VELOCIDAD DEL PERSONAJE
VELOCIDAD_GATO = 4
GRAVEDAD = 0.6
VELOCIDAD_SALTO = -12

VIDAS_MAXIMAS = 7

# TAMAÑO DE LOS TILES
TILE_SIZE = 64

# CARBONES
VELOCIDAD_CARBON = 4
FRECUENCIA_CARBON_MS = 3500   # en milisegundos
